stages:
  - unit
  - acceptance

# Cache libraries in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/

codeception:
  stage: acceptance
  tags:
    - juice
  script:
     - "docker stop $(docker ps -a -q)"
     - "docker-compose build"
     - "docker-compose run --rm codeception run -vvv --html --fail-fast"
  artifacts:
    when: on_failure
    paths:
      - tests/acceptance-tests/_output/
    expire_in: 1 week

phpunit:
  stage: unit
  image: wordpress:4.9.8-php7.1
  script:
  - apt-get update -yqq
  - apt-get install git -yqq # Install git, the php image doesn't have installed
  - apt-get -yqqf install vim wget zip unzip subversion mysql-client libmcrypt-dev --fix-missing # instll the required packages for the running CI tests.
  - curl -sS https://getcomposer.org/installer | php # Install composer
  - php composer.phar install # Install all project dependencies
  - vendor/bin/phpunit --bootstrap tests-bootstrap.php tests/includes/EmailTelemetryTest
