stages:
  - Integration
  - unit

# Cache libraries in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - node_modules/

# Variables
variables:
  # For the MySQL Service Used By WordPress Tests
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql
  DB_HOST: mysql


# PHP "Unit" Tests With WordPress
PHP Unit Tests:
  stage: unit
  image: wordpress:5.4.0-php7.3-fpm
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq mariadb-client # install Mariadb client
    - apt-get install git -yqq # Install git, the php image doesn't have installed
    - apt-get -yqqf install vim wget zip unzip subversion libmcrypt-dev --fix-missing # instll the required packages for the running CI tests.
    - curl -sS https://getcomposer.org/installer | php # Install composer
    - php composer.phar install # Install all project dependencies
  script:
    - vendor/bin/phpunit -c phpunit-ci.xml.dist

# JavaScript Unit Tests Without WordPress
JavaScript Tests:
  stage: unit
  image: node:latest
  before_script:
    - yarn
  script:
    - yarn test:ci

# WordPress Integration Tests
## Based on https://git.saturdaydrive.io/_/engineering-ops/sd-email-crm/email-crm/blob/master/.gitlab-ci.yml#L110
Integration:
  stage: Integration
  image: calevans/docker:php7.3
  services:
    - mysql:5.6
  before_script:
    - bash bin/install_gitlab_tests.sh wordpress_tests root mysql mysql latest
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - composer require johnpbloch/wordpress --prefer-dist
  script:
    - vendor/bin/phpunit tests/integration --bootstrap tests/bootstrap-integration.php