language: php
sudo: true
dist: trusty

addons:
  hosts:
    - ninjaforms.test

jdk:
  - oraclejdk8

php:
  - 7.0

before_install:
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz"
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - mysql -e 'CREATE DATABASE wp;'
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - chmod +x ./bin/install-apache.sh
  - sudo bash ./bin/install-apache.sh
  - chmod +x ./bin/install-wp.sh
  - bash ./bin/install-wp.sh --dir="/tmp/wp" --dbname="wp" --dbuser="root" --dbpass="" --dbprefix="wp_" --domain="ninjaforms.test" --title="Test" --admin_user="admin" --admin_password="admin" --admin_email="admin@wordpress.dev" --theme="twentysixteen" --empty
  - sudo cp -R /tmp/wp/* /var/www/html/
  - sudo rm /var/www/html/index.html
  - composer update
  - sudo cp -R ../ninja-forms /var/www/html/wp-content/mu-plugins/

before_script:
  - "wget -P /tmp http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar"
  - "java -jar /tmp/selenium-server-standalone-3.4.0.jar > /dev/null &"
  - sleep 5
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - bin/codecept run acceptance