language: php
sudo: true
dist: trusty

jdk:
  - oraclejdk8

php:
  - 7.0

install:
  - mysql -e 'CREATE DATABASE wp;'
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - git clone https://github.com/lucatume/travis-apache-setup.git setup
  - chmod +x ./setup/apache-setup.sh
  - sudo bash ./setup/apache-setup.sh -d="/var/www/" -h="127.0.0.1" -u="http://localhost"
  - chmod +x ./setup/wp-install.sh
  - sudo bash ./setup/wp-install.sh --dir="/var/www/" --dbname="wp" --dbuser="root" --dbpass="" --dbprefix="wp_" --domain="localhost" --title="Test" --admin_user="admin" --admin_password="admin" --admin_email="admin@wordpress.dev" --theme="twentysixteen" --empty
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - composer update

script:
  - bin/codecept run acceptance