version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8228:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DEBUG: 1
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress:/var/www/html
      - ..:/var/www/html/wp-content/plugins/ninja-forms
      - .:/var/www/html/wp-content/plugins/ninja-forms-blocks
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins

  cli:
    image: wordpress:cli
    volumes:
    - wordpress:/var/www/html
    - .:/var/www/html/wp-content/plugins/ninja-forms-blocks
    - ./wp-content/plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress

  wordpress_phpunit:
    image: chriszarate/wordpress-phpunit
    environment:
      PHPUNIT_DB_HOST: mysql
    volumes:
      - .:/app
      - testsuite:/tmp

  composer:
    image: composer
    volumes:
      - .:/app

volumes:
  testsuite:
  wordpress: